### ISSUE TITLE
Hi，girl

### ISSUE THREAD

**Issue by time-river** [nanf0621/nanf0621.github.io#1]
就不能勤快点嘛，想看一点新的东西

**Comment by nanf0621** [comment]
好啊。以及我的域名回来了
nanf.me


发自网易邮箱大师

在2017年03月16日 10:47，time-river<mailto:notifications@github.com> 写道：

就不能勤快点嘛，想看一点新的东西

**Comment by time-river** [comment]
Lively girl ;)On Mar 17, 2017 20:53, nanf0621 <notifications@github.com> wrote:好啊。以及我的域名回来了

nanf.me





发自网易邮箱大师



在2017年03月16日 10:47，time-river<mailto:notifications@github.com> 写道：



就不能勤快点嘛，想看一点新的东西

**Comment by time-river** [comment]
病句：
已经打铁惨淡退役的前ACMer
退役的前
类型：？？
反正是病句

**Comment by nanf0621** [comment]
哦。懒得改。


发自网易邮箱大师

在2017年03月18日 10:19，time-river<mailto:notifications@github.com> 写道：

病句：
已经打铁惨淡退役的前ACMer
退役的前
类型：？？
反正是病句

**Comment by time-river** [comment]
You are too lazy, there are too few and invariant articles seen I am here every time.
I want to read your new article.
